<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsn-br="http://docs.oasis-open.org/wsn/br-2" xmlns:wsn-brw="http://docs.oasis-open.org/wsn/brw-2" xmlns:wsn-b="http://docs.oasis-open.org/wsn/b-2" xmlns:wsn-bw="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsrf-rpw="http://docs.oasis-open.org/wsrf/rpw-2" xmlns:tns="http://robinjam.net/aes/wsn/jaxws" name="AES-WS-BrokeredNotification" targetNamespace="http://robinjam.net/aes/wsn/jaxws">
    <wsdl:import namespace="http://docs.oasis-open.org/wsn/brw-2" location="http://docs.oasis-open.org/wsn/brw-2.wsdl">
        </wsdl:import>
    <wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2" location="http://docs.oasis-open.org/wsn/bw-2.wsdl">
        </wsdl:import>
    <wsdl:import namespace="http://docs.oasis-open.org/wsrf/rpw-2" location="http://docs.oasis-open.org/wsrf/rpw-2.wsdl">
    </wsdl:import>
    <wsdl:binding name="NotificationBrokerSoap" type="wsn-brw:NotificationBroker">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="Notify">
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="Subscribe">
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ResourceUnknownFault">
                <soap:fault use="literal" name="ResourceUnknownFault"/>
            </wsdl:fault>
            <wsdl:fault name="InvalidFilterFault">
                <soap:fault use="literal" name="InvalidFilterFault"/>
            </wsdl:fault>
            <wsdl:fault name="TopicExpressionDialectUnknownFault">
                <soap:fault use="literal" name="TopicExpressionDialectUnknownFault"/>
            </wsdl:fault>
            <wsdl:fault name="InvalidTopicExpressionFault">
                <soap:fault use="literal" name="InvalidTopicExpressionFault"/>
            </wsdl:fault>
            <wsdl:fault name="TopicNotSupportedFault">
                <soap:fault use="literal" name="TopicNotSupportedFault"/>
            </wsdl:fault>
            <wsdl:fault name="InvalidProducerPropertiesExpressionFault">
                <soap:fault use="literal" name="InvalidProducerPropertiesExpressionFault"/>
            </wsdl:fault>
            <wsdl:fault name="InvalidMessageContentExpressionFault">
                <soap:fault use="literal" name="InvalidMessageContentExpressionFault"/>
            </wsdl:fault>
            <wsdl:fault name="UnacceptableInitialTerminationTimeFault">
                <soap:fault use="literal" name="UnacceptableInitialTerminationTimeFault"/>
            </wsdl:fault>
            <wsdl:fault name="SubscribeCreationFailedFault">
                <soap:fault use="literal" name="SubscribeCreationFailedFault"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="GetCurrentMessage">
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ResourceUnknownFault">
                <soap:fault use="literal" name="ResourceUnknownFault"/>
            </wsdl:fault>
            <wsdl:fault name="TopicExpressionDialectUnknownFault">
                <soap:fault use="literal" name="TopicExpressionDialectUnknownFault"/>
            </wsdl:fault>
            <wsdl:fault name="InvalidTopicExpressionFault">
                <soap:fault use="literal" name="InvalidTopicExpressionFault"/>
            </wsdl:fault>
            <wsdl:fault name="TopicNotSupportedFault">
                <soap:fault use="literal" name="TopicNotSupportedFault"/>
            </wsdl:fault>
            <wsdl:fault name="NoCurrentMessageOnTopicFault">
                <soap:fault use="literal" name="NoCurrentMessageOnTopicFault"/>
            </wsdl:fault>
            <wsdl:fault name="MultipleTopicsSpecifiedFault">
                <soap:fault use="literal" name="MultipleTopicsSpecifiedFault"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="RegisterPublisher">
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ResourceUnknownFault">
                <soap:fault use="literal" name="ResourceUnknownFault"/>
            </wsdl:fault>
            <wsdl:fault name="InvalidTopicExpressionFault">
                <soap:fault use="literal" name="InvalidTopicExpressionFault"/>
            </wsdl:fault>
            <wsdl:fault name="TopicNotSupportedFault">
                <soap:fault use="literal" name="TopicNotSupportedFault"/>
            </wsdl:fault>
            <wsdl:fault name="PublisherRegistrationRejectedFault">
                <soap:fault use="literal" name="PublisherRegistrationRejectedFault"/>
            </wsdl:fault>
            <wsdl:fault name="PublisherRegistrationFailedFault">
                <soap:fault use="literal" name="PublisherRegistrationFailedFault"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="NotificationBrokerService">
        <wsdl:port name="NotificationBrokerPort" binding="tns:NotificationBrokerSoap">
            <soap:address location="http://robinjam.net/aes/wsnotification"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
